import { Course } from "@/types";

export const MOCK_COURSES: Course[] = [
  // Semester 1
  {
    id: "cse-1101",
    code: "CSE 1101",
    name: "Structured Programming Language",
    credits: 3.0,
    semester: 1,
    department: "CSE",
    type: "Theory",
    description: "Fundamental concepts of procedural programming, variables, control flow, functions, arrays, and pointers in C.",
  },
  {
    id: "cse-1102",
    code: "CSE 1102",
    name: "Structured Programming Language Lab",
    credits: 1.5,
    semester: 1,
    department: "CSE",
    type: "Lab",
    description: "Hands-on problem solving, algorithmic thinking, and debugging with C language.",
  },
  {
    id: "mat-1101",
    code: "MAT 1101",
    name: "Differential and Integral Calculus",
    credits: 3.0,
    semester: 1,
    department: "CSE",
    type: "Theory",
    description: "Limits, continuity, differentiation, integration, techniques and engineering applications.",
  },
  {
    id: "phy-1103",
    code: "PHY 1103",
    name: "Physics (Waves, Optics & Thermodynamics)",
    credits: 3.0,
    semester: 1,
    department: "CSE",
    type: "Theory",
    description: "Oscillations, wave motion, geometric optics, wave optics, laws of thermodynamics and heat engines.",
  },
  // Semester 2
  {
    id: "cse-1203",
    code: "CSE 1203",
    name: "Object Oriented Programming",
    credits: 3.0,
    semester: 2,
    department: "CSE",
    type: "Theory",
    description: "Principles of OOP: Encapsulation, inheritance, polymorphism, abstraction, exception handling in Java.",
  },
  {
    id: "cse-1204",
    code: "CSE 1204",
    name: "Object Oriented Programming Lab",
    credits: 1.5,
    semester: 2,
    department: "CSE",
    type: "Lab",
    description: "Building robust desktop applications and OOP design implementations.",
  },
  {
    id: "mat-1201",
    code: "MAT 1201",
    name: "Linear Algebra & Differential Equations",
    credits: 3.0,
    semester: 2,
    department: "CSE",
    type: "Theory",
    description: "Matrices, determinants, eigenvalues, eigenvectors, first and second order differential equations.",
  },
  // Semester 3
  {
    id: "cse-2203",
    code: "CSE 2203",
    name: "Data Structures and Algorithms",
    credits: 3.0,
    semester: 3,
    department: "CSE",
    type: "Theory",
    description: "Stacks, queues, linked lists, trees, heaps, graphs, hashing, sorting, and asymptotic analysis.",
  },
  {
    id: "cse-2204",
    code: "CSE 2204",
    name: "Data Structures and Algorithms Lab",
    credits: 1.5,
    semester: 3,
    department: "CSE",
    type: "Lab",
    description: "Practical implementations of classic data structures, recursion, and search/sort benchmarks.",
  },
  {
    id: "cse-2205",
    code: "CSE 2205",
    name: "Discrete Mathematics",
    credits: 3.0,
    semester: 3,
    department: "CSE",
    type: "Theory",
    description: "Set theory, propositional logic, mathematical induction, recurrence relations, graph theory.",
  },
  // Semester 4
  {
    id: "cse-2301",
    code: "CSE 2301",
    name: "Database Management Systems",
    credits: 3.0,
    semester: 4,
    department: "CSE",
    type: "Theory",
    description: "Relational model, SQL, normalization, transactions, concurrency control, and indexing.",
  },
  {
    id: "cse-2302",
    code: "CSE 2302",
    name: "Database Management Systems Lab",
    credits: 1.5,
    semester: 4,
    department: "CSE",
    type: "Lab",
    description: "Schema design, complex SQL querying, stored procedures, triggers, and full-stack database connection.",
  },
  {
    id: "cse-2303",
    code: "CSE 2303",
    name: "Design and Analysis of Algorithms",
    credits: 3.0,
    semester: 4,
    department: "CSE",
    type: "Theory",
    description: "Divide-and-conquer, greedy algorithms, dynamic programming, graph algorithms, and NP-completeness.",
  },
  // Semester 5 (Current Regular Courses)
  {
    id: "cse-3301",
    code: "CSE 3301",
    name: "Software Engineering & Design",
    credits: 3.0,
    semester: 5,
    department: "CSE",
    type: "Theory",
    description: "Agile methodologies, SDLC, requirements engineering, architectural design patterns, software testing.",
  },
  {
    id: "cse-3302",
    code: "CSE 3302",
    name: "Software Engineering & Design Lab",
    credits: 1.5,
    semester: 5,
    department: "CSE",
    type: "Lab",
    description: "End-to-end team project development, CI/CD pipeline, automated testing, and sprint delivery.",
  },
  {
    id: "cse-3303",
    code: "CSE 3303",
    name: "Operating Systems Principles",
    credits: 3.0,
    semester: 5,
    department: "CSE",
    type: "Theory",
    description: "Process management, CPU scheduling, synchronization, deadlocks, memory management, virtual memory, file systems.",
  },
  {
    id: "cse-3304",
    code: "CSE 3304",
    name: "Operating Systems Principles Lab",
    credits: 1.5,
    semester: 5,
    department: "CSE",
    type: "Lab",
    description: "Linux shell scripting, POSIX threads, inter-process communication, and kernel system calls.",
  },
  {
    id: "cse-3305",
    code: "CSE 3305",
    name: "Microprocessors & Embedded Systems",
    credits: 3.0,
    semester: 5,
    department: "CSE",
    type: "Theory",
    description: "8086 architecture, assembly language programming, interrupt handling, interfacing, and ARM microcontroller basics.",
  },
  {
    id: "cse-3306",
    code: "CSE 3306",
    name: "Microprocessors & Embedded Systems Lab",
    credits: 1.5,
    semester: 5,
    department: "CSE",
    type: "Lab",
    description: "Assembly language programming emulators, hardware timers, ADC/DAC sensors, and IoT prototyping.",
  },
];
