import { ClassSession } from "@/types";

/**
 * RASH's baseline regular routine:
 * Batch 62, Section H (Fall 2026)
 */
export const MOCK_REGULAR_ROUTINE: ClassSession[] = [
  // Sunday
  {
    id: "reg-sun-1",
    courseCode: "CSE 3301",
    courseName: "Software Engineering & Design",
    batch: "62",
    section: "H",
    type: "Theory",
    day: "Sunday",
    startTime: "11:30",
    endTime: "13:00",
    room: "Room 502",
    faculty: "Dr. Fahim Rahman",
    enrollmentType: "Regular",
  },
  {
    id: "reg-sun-2",
    courseCode: "CSE 3302",
    courseName: "Software Engineering & Design Lab",
    batch: "62",
    section: "H",
    type: "Lab",
    day: "Sunday",
    startTime: "14:00",
    endTime: "16:30",
    room: "Lab 304",
    faculty: "Ms. Sadia Islam",
    enrollmentType: "Regular",
  },

  // Monday
  {
    id: "reg-mon-1",
    courseCode: "CSE 3303",
    courseName: "Operating Systems Principles",
    batch: "62",
    section: "H",
    type: "Theory",
    day: "Monday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 502",
    faculty: "Prof. Tariq Ahmed",
    enrollmentType: "Regular",
  },
  {
    id: "reg-mon-2",
    courseCode: "CSE 3304",
    courseName: "Operating Systems Principles Lab",
    batch: "62",
    section: "H",
    type: "Lab",
    day: "Monday",
    startTime: "11:30",
    endTime: "14:00",
    room: "Lab 302",
    faculty: "Prof. Tariq Ahmed",
    enrollmentType: "Regular",
  },

  // Tuesday
  {
    id: "reg-tue-1",
    courseCode: "CSE 3305",
    courseName: "Microprocessors & Embedded Systems",
    batch: "62",
    section: "H",
    type: "Theory",
    day: "Tuesday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 502",
    faculty: "Dr. Nazmul Hossain",
    enrollmentType: "Regular",
  },
  {
    id: "reg-tue-2",
    courseCode: "CSE 3301",
    courseName: "Software Engineering & Design",
    batch: "62",
    section: "H",
    type: "Theory",
    day: "Tuesday",
    startTime: "11:30",
    endTime: "13:00",
    room: "Room 502",
    faculty: "Dr. Fahim Rahman",
    enrollmentType: "Regular",
  },

  // Wednesday
  {
    id: "reg-wed-1",
    courseCode: "CSE 3303",
    courseName: "Operating Systems Principles",
    batch: "62",
    section: "H",
    type: "Theory",
    day: "Wednesday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 502",
    faculty: "Prof. Tariq Ahmed",
    enrollmentType: "Regular",
  },

  // Thursday
  {
    id: "reg-thu-1",
    courseCode: "CSE 3305",
    courseName: "Microprocessors & Embedded Systems",
    batch: "62",
    section: "H",
    type: "Theory",
    day: "Thursday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 502",
    faculty: "Dr. Nazmul Hossain",
    enrollmentType: "Regular",
  },
  {
    id: "reg-thu-2",
    courseCode: "CSE 3306",
    courseName: "Microprocessors & Embedded Systems Lab",
    batch: "62",
    section: "H",
    type: "Lab",
    day: "Thursday",
    startTime: "11:30",
    endTime: "14:00",
    room: "Lab 306",
    faculty: "Dr. Nazmul Hossain",
    enrollmentType: "Regular",
  },
];

/**
 * All junior batch sections and class offerings available for retake / improvement.
 * Staged to demonstrate real conflicts and optimal alternatives.
 */
export const MOCK_AVAILABLE_OFFERINGS: ClassSession[] = [
  // ==========================================
  // CSE 2203: Data Structures and Algorithms (Theory, 3 Cr)
  // ==========================================
  // Batch 62 - Section A (CONFLITING with CSE 3301 on Sun 11:30 & Tue 11:30)
  {
    id: "off-cse2203-62-a-1",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "62",
    section: "A",
    type: "Theory",
    day: "Sunday",
    startTime: "11:00",
    endTime: "12:30",
    room: "Room 301",
    faculty: "Dr. Anisul Islam",
  },
  {
    id: "off-cse2203-62-a-2",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "62",
    section: "A",
    type: "Theory",
    day: "Tuesday",
    startTime: "11:00",
    endTime: "12:30",
    room: "Room 301",
    faculty: "Dr. Anisul Islam",
  },

  // Batch 62 - Section B (CONFLITING with OS Lab on Mon 11:30-14:00)
  {
    id: "off-cse2203-62-b-1",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "62",
    section: "B",
    type: "Theory",
    day: "Monday",
    startTime: "12:00",
    endTime: "13:30",
    room: "Room 302",
    faculty: "Ms. Nafisa Haque",
  },
  {
    id: "off-cse2203-62-b-2",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "62",
    section: "B",
    type: "Theory",
    day: "Wednesday",
    startTime: "11:30",
    endTime: "13:00",
    room: "Room 302",
    faculty: "Ms. Nafisa Haque",
  },

  // Batch 62 - Section C (COMPATIBLE ALTERNATIVE: Tuesday & Thursday afternoons)
  {
    id: "off-cse2203-62-c-1",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "62",
    section: "C",
    type: "Theory",
    day: "Tuesday",
    startTime: "14:30",
    endTime: "16:00",
    room: "C-302",
    faculty: "Dr. M. Rahman",
  },
  {
    id: "off-cse2203-62-c-2",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "62",
    section: "C",
    type: "Theory",
    day: "Thursday",
    startTime: "14:30",
    endTime: "16:00",
    room: "C-302",
    faculty: "Dr. M. Rahman",
  },

  // Batch 63 - Section B (COMPATIBLE ALTERNATIVE: Morning slots)
  {
    id: "off-cse2203-63-b-1",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "63",
    section: "B",
    type: "Theory",
    day: "Sunday",
    startTime: "08:00",
    endTime: "09:30",
    room: "Room 304",
    faculty: "Dr. Farzana Kabir",
  },
  {
    id: "off-cse2203-63-b-2",
    courseCode: "CSE 2203",
    courseName: "Data Structures and Algorithms",
    batch: "63",
    section: "B",
    type: "Theory",
    day: "Wednesday",
    startTime: "11:30",
    endTime: "13:00",
    room: "Room 304",
    faculty: "Dr. Farzana Kabir",
  },

  // ==========================================
  // CSE 2204: Data Structures Lab (1.5 Cr)
  // ==========================================
  {
    id: "off-cse2204-62-a",
    courseCode: "CSE 2204",
    courseName: "Data Structures and Algorithms Lab",
    batch: "62",
    section: "A",
    type: "Lab",
    day: "Sunday",
    startTime: "14:00",
    endTime: "16:30",
    room: "Lab 301",
    faculty: "Dr. Anisul Islam",
  },
  {
    id: "off-cse2204-62-b",
    courseCode: "CSE 2204",
    courseName: "Data Structures and Algorithms Lab",
    batch: "62",
    section: "B",
    type: "Lab",
    day: "Tuesday",
    startTime: "14:00",
    endTime: "16:30",
    room: "Lab 303",
    faculty: "Ms. Nafisa Haque",
  },
  {
    id: "off-cse2204-63-a",
    courseCode: "CSE 2204",
    courseName: "Data Structures and Algorithms Lab",
    batch: "63",
    section: "A",
    type: "Lab",
    day: "Wednesday",
    startTime: "14:00",
    endTime: "16:30",
    room: "Lab 305",
    faculty: "Dr. Farzana Kabir",
  },

  // ==========================================
  // MAT 1201: Linear Algebra & Differential Equations (Theory, 3 Cr)
  // ==========================================
  // Batch 62 - Section A (Conflict on Tue 09:30-11:00 with Microprocessors)
  {
    id: "off-mat1201-62-a-1",
    courseCode: "MAT 1201",
    courseName: "Linear Algebra & Differential Equations",
    batch: "62",
    section: "A",
    type: "Theory",
    day: "Sunday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 401",
    faculty: "Prof. Shamsul Alam",
  },
  {
    id: "off-mat1201-62-a-2",
    courseCode: "MAT 1201",
    courseName: "Linear Algebra & Differential Equations",
    batch: "62",
    section: "A",
    type: "Theory",
    day: "Tuesday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 401",
    faculty: "Prof. Shamsul Alam",
  },

  // Batch 62 - Section C (COMPATIBLE: Sun 09:30 & Wed 14:00)
  {
    id: "off-mat1201-62-c-1",
    courseCode: "MAT 1201",
    courseName: "Linear Algebra & Differential Equations",
    batch: "62",
    section: "C",
    type: "Theory",
    day: "Sunday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 403",
    faculty: "Dr. Mahmuda Begum",
  },
  {
    id: "off-mat1201-62-c-2",
    courseCode: "MAT 1201",
    courseName: "Linear Algebra & Differential Equations",
    batch: "62",
    section: "C",
    type: "Theory",
    day: "Wednesday",
    startTime: "14:00",
    endTime: "15:30",
    room: "Room 403",
    faculty: "Dr. Mahmuda Begum",
  },

  // Batch 63 - Section B (COMPATIBLE: Mon & Thu afternoon)
  {
    id: "off-mat1201-63-b-1",
    courseCode: "MAT 1201",
    courseName: "Linear Algebra & Differential Equations",
    batch: "63",
    section: "B",
    type: "Theory",
    day: "Monday",
    startTime: "14:30",
    endTime: "16:00",
    room: "Room 405",
    faculty: "Dr. Mahmuda Begum",
  },
  {
    id: "off-mat1201-63-b-2",
    courseCode: "MAT 1201",
    courseName: "Linear Algebra & Differential Equations",
    batch: "63",
    section: "B",
    type: "Theory",
    day: "Thursday",
    startTime: "14:30",
    endTime: "16:00",
    room: "Room 405",
    faculty: "Dr. Mahmuda Begum",
  },

  // ==========================================
  // PHY 1103: Physics (Theory, 3 Cr)
  // ==========================================
  {
    id: "off-phy1103-63-a-1",
    courseCode: "PHY 1103",
    courseName: "Physics (Waves, Optics & Thermodynamics)",
    batch: "63",
    section: "A",
    type: "Theory",
    day: "Monday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 201",
    faculty: "Dr. Kamrul Hasan",
  },
  {
    id: "off-phy1103-63-a-2",
    courseCode: "PHY 1103",
    courseName: "Physics (Waves, Optics & Thermodynamics)",
    batch: "63",
    section: "A",
    type: "Theory",
    day: "Wednesday",
    startTime: "09:30",
    endTime: "11:00",
    room: "Room 201",
    faculty: "Dr. Kamrul Hasan",
  },
  // Batch 63 - Section B (COMPATIBLE)
  {
    id: "off-phy1103-63-b-1",
    courseCode: "PHY 1103",
    courseName: "Physics (Waves, Optics & Thermodynamics)",
    batch: "63",
    section: "B",
    type: "Theory",
    day: "Tuesday",
    startTime: "14:30",
    endTime: "16:00",
    room: "Room 203",
    faculty: "Dr. Kamrul Hasan",
  },
  {
    id: "off-phy1103-63-b-2",
    courseCode: "PHY 1103",
    courseName: "Physics (Waves, Optics & Thermodynamics)",
    batch: "63",
    section: "B",
    type: "Theory",
    day: "Wednesday",
    startTime: "14:00",
    endTime: "15:30",
    room: "Room 203",
    faculty: "Dr. Kamrul Hasan",
  },

  // ==========================================
  // CSE 1101: Structured Programming (Theory, 3 Cr)
  // ==========================================
  {
    id: "off-cse1101-63-c-1",
    courseCode: "CSE 1101",
    courseName: "Structured Programming Language",
    batch: "63",
    section: "C",
    type: "Theory",
    day: "Wednesday",
    startTime: "11:30",
    endTime: "13:00",
    room: "Room 105",
    faculty: "Ms. Samira Khan",
  },
  {
    id: "off-cse1101-63-c-2",
    courseCode: "CSE 1101",
    courseName: "Structured Programming Language",
    batch: "63",
    section: "C",
    type: "Theory",
    day: "Thursday",
    startTime: "14:30",
    endTime: "16:00",
    room: "Room 105",
    faculty: "Ms. Samira Khan",
  },
];
